// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCilNxI88-vxDnbx6Ul5NuUjphV8FnmywM',
    appId: '1:1013758906280:web:c0f03eead9b16d9971579d',
    messagingSenderId: '1013758906280',
    projectId: 'eat-me-9145b',
    authDomain: 'eat-me-9145b.firebaseapp.com',
    storageBucket: 'eat-me-9145b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnvlA2dgS5AEjs2gnKe3FOkOJMmpu278',
    appId: '1:1013758906280:android:fb7ecc05dfa597e971579d',
    messagingSenderId: '1013758906280',
    projectId: 'eat-me-9145b',
    storageBucket: 'eat-me-9145b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxGJHMIAvJLik_mfes6Oyadn7T7Q6rz8',
    appId: '1:1013758906280:ios:3d59d04df168b7de71579d',
    messagingSenderId: '1013758906280',
    projectId: 'eat-me-9145b',
    storageBucket: 'eat-me-9145b.appspot.com',
    iosBundleId: 'com.example.eatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRxGJHMIAvJLik_mfes6Oyadn7T7Q6rz8',
    appId: '1:1013758906280:ios:979b1736b2e1fe1c71579d',
    messagingSenderId: '1013758906280',
    projectId: 'eat-me-9145b',
    storageBucket: 'eat-me-9145b.appspot.com',
    iosBundleId: 'com.example.eatMe.RunnerTests',
  );
}
